language: java
script: mvn package
deploy:
  provider: script
  script: ./travis/deploy.sh
  on:
    branch: master

env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
    # OSSRH_JIRA_PASSWORD
  - secure: G2AzjrgXiGcR0Xgm2KtAfSDOT0FhVw5BYFWca0KUmXR6gFOzqQ0qxmAuwoc/vcslVR1yHCtpRjQ37K0hGm/T22XiM4cjGyTTRb0ZYpcJcDxAHSttDuXknu5DBTLRZ80ddKoZhm2ariyS5egKBxfuZxrKm/gJosvvoWq9ykXKvgahX8Dad+WQJPLR5e1QgrzkehVqX/ApMsAA2cd7j2Yk9LbkI783n3ZGcJVdpY4tFwbW9EjWZOqkzT9IZ5nHJ2KnGjIWMwvvXyvxH07kDD15iP+ZwHMCOPtCiuurfjJu2C/tOVyGX/Wpi1yfYrYSKkDXw4q/o2LE08hSnlO5qGVaJoqaaekPw8CzhX5bNTeD4LjPSjseHA/mTEn8TtqNbVUozv58KrGPJWcV7pn9v20Ivytg6Yi2jPuQBfEooIIj48WDEImf2zDiUks+XYxVWr8uqr9uPjrqTO/KA6YEjeLI2xvFI5GJgW0QjyqBkkaI6qtpbcez39WvJDd/w2Xucm8PaVA383Lt0wdUmPBK2ogu1PMO+BRkd14XFdKI42QjSbQ7eEVs6j06feChBvMRmnOdMEprLc8RuYfoKIxpSvGYEWv8wKSY4mriijFd6K6Qc9G0vU5L/k40KOBaiHBCZCegHzRAKdMc7ZCDXYkxkrTYdf6y0Hc/k8DvnP4TK3Osp+0=
  - GPG_KEY_NAME=navikt
    # GPG_PASSPHRASE
  - secure: UUB+wb/0KIODFWZJ2EKaPcii/AfQfnfeM9Q2Wv31AObW7jiUfCqVyqPcgcz5C2+0O60KsEBDF8BVybe8HaOmeizrA1t2kAyJfo7G3kFuIQM+umPSw81Jk3WYxjPyPgYs2LT4QXzB6ZUFIlQU2pRvd8cAtLo7RJmnCPe67aDO/Fl2XJdPxYxYH2WMgtgaTVXQt6i4sn8UUNmmT6Z10MxCLOL1nkJD3leleZEf8ZjBWKaA2FEzrKJxxwLE0MqoHvXHBW7jqopc4QtTHOqDu16Mf2ELOVj9U5L+HNFM46sYBHaxU0jFFb/uCD5B3mCiyK1Tllr5obtoYsVLNLpVrbDXLft2jWt+viTz8FiCRM74S+ILPOOhaJU7LK5JC+57nsS+AHbyr8kwAyg/RZ1GSadJ1gARkv8fxoZ2upxJh0y6tXGQ1CbmbgvMxIRybiIojZAqvPfQtVu9+0iC/rPao2iyvU/cIc862W9R0GogVLlR89s6bAJ+bBgqkzun0VfgoNheBxB5/smzZtyeqBf9BZpZYIiO22AZTPLcF8Sq49FPJZGxprZo9UrFQi9+GJB4AtxUS8yupyNq8jyf4RZ6LHZDkCBJ71YzrfkVrySIr3/sc+E0LRd49G7mkElnjngba2k+z1Dw6qzeeVR0achsYvu9HS+dBKzVzBUri93KDtFTWAA=
